# Generated by Django 5.1.1 on 2025-10-01 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_authority_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('state_chairman', 'State Chairman'), ('district_chairman', 'District Chairman'), ('nagar_panchayat_chairman', 'Nagar Panchayat Chairman'), ('village_sarpanch', 'Village Sarpanch'), ('other', 'Other'), ('admin', 'Admin')], default='user', max_length=50),
        ),
        migrations.CreateModel(
            name='SubAuthority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_sub_authorities', to=settings.AUTH_USER_MODEL)),
                ('sub_authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_as_sub_authority', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('creator', 'sub_authority')},
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=200, null=True)),
                ('permissions', models.JSONField(blank=True, default=dict)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('authority', 'member')},
            },
        ),
    ]
