# Generated by Django 5.1.1 on 2025-10-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='authority_level',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='current_designation',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='location',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='service_card_proof',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='taluka',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
