# Generated by Django 5.1.1 on 2025-10-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_customuser_authority_level_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subauthority',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='subauthority',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subauthority',
            name='can_approve_reports',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subauthority',
            name='can_manage_teams',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subauthority',
            name='can_view_reports',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subauthority',
            name='custom_role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subauthority',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subauthority',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='subauthority',
            name='first_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='subauthority',
            name='government_service_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subauthority',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='subauthority',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subauthority',
            name='nagar_panchayat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subauthority',
            name='password_hash',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='subauthority',
            name='phone_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='subauthority',
            name='role',
            field=models.CharField(choices=[('state_chairman', 'State Chairman'), ('district_chairman', 'District Chairman'), ('nagar_panchayat_chairman', 'Nagar Panchayat Chairman'), ('village_sarpanch', 'Village Sarpanch'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='subauthority',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subauthority',
            name='village',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='subauthority',
            name='sub_authority',
        ),
    ]
