# Generated by Django 5.1.1 on 2025-10-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_subauthority_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subauthority',
            name='document_proof',
            field=models.FileField(blank=True, null=True, upload_to='sub_authority_documents/'),
        ),
    ]
