# Generated by Django 5.2 on 2025-10-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_teammember_unique_together_teammember_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='service_card_proof',
            field=models.FileField(blank=True, null=True, upload_to='authority_documents/'),
        ),
    ]
