# Generated by Django 5.2 on 2025-10-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_customuser_service_card_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_login_time',
            field=models.DateTimeField(blank=True, help_text='Last time the user logged in', null=True),
        ),
    ]
