# Generated by Django 5.2 on 2025-10-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_customuser_last_login_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='current_designation',
            field=models.CharField(blank=True, help_text='Current job designation/title', max_length=200, null=True),
        ),
    ]
