# Generated by Django 5.2 on 2025-10-03 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_refreshtoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="OceanHazardReport",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("report_id", models.CharField(blank=True, max_length=20, unique=True)),
                (
                    "hazard_type",
                    models.CharField(
                        choices=[
                            ("tsunami", "Tsunami Warning"),
                            ("storm-surge", "Storm Surge"),
                            ("high-waves", "High Waves"),
                            ("flooding", "Coastal Flooding"),
                            ("debris", "Marine Debris"),
                            ("pollution", "Water Pollution"),
                            ("erosion", "Coastal Erosion"),
                            ("wildlife", "Marine Wildlife Issue"),
                            ("other", "Other Hazard"),
                        ],
                        help_text="Type of ocean hazard reported",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed description of the hazard"),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=8,
                        help_text="GPS latitude coordinate",
                        max_digits=10,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=8,
                        help_text="GPS longitude coordinate",
                        max_digits=11,
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        help_text="Country where hazard occurred", max_length=100
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        help_text="State/Province where hazard occurred", max_length=100
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        help_text="District where hazard occurred", max_length=100
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        help_text="City/Town where hazard occurred", max_length=100
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True, help_text="Detailed address if available", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("verified", "Verified"),
                            ("discarded", "Discarded"),
                            ("under_investigation", "Under Investigation"),
                            ("resolved", "Resolved"),
                        ],
                        default="pending",
                        help_text="Current status of the hazard report",
                        max_length=30,
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the hazard has been verified by authorities",
                    ),
                ),
                (
                    "review_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes from the reviewing official",
                        null=True,
                    ),
                ),
                (
                    "reported_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the report was submitted"
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the report was reviewed by an official",
                        null=True,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When the report was last updated"
                    ),
                ),
                (
                    "ai_verification_score",
                    models.FloatField(
                        blank=True,
                        help_text="AI verification confidence score",
                        null=True,
                    ),
                ),
                (
                    "ai_verification_details",
                    models.JSONField(
                        blank=True,
                        help_text="Detailed AI verification results",
                        null=True,
                    ),
                ),
                (
                    "emergency_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        help_text="Assessed emergency level of the hazard",
                        max_length=10,
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this report is publicly visible",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Tags for categorization and search",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        help_text="The citizen who submitted this hazard report",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hazard_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Official who reviewed/acted on this report",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_hazard_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ocean Hazard Report",
                "verbose_name_plural": "Ocean Hazard Reports",
                "ordering": ["-reported_at"],
            },
        ),
        migrations.CreateModel(
            name="HazardImage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "image_file",
                    models.ImageField(
                        help_text="The actual image file",
                        upload_to="hazard_images/%Y/%m/%d/",
                    ),
                ),
                (
                    "image_type",
                    models.CharField(
                        choices=[
                            ("primary", "Primary Image"),
                            ("evidence", "Evidence Image"),
                            ("damage", "Damage Documentation"),
                            ("location", "Location Reference"),
                            ("other", "Other"),
                        ],
                        default="evidence",
                        help_text="Type/category of this image",
                        max_length=20,
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True,
                        help_text="Optional caption for the image",
                        max_length=200,
                    ),
                ),
                (
                    "image_latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        help_text="GPS latitude from image EXIF data",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "image_longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        help_text="GPS longitude from image EXIF data",
                        max_digits=11,
                        null=True,
                    ),
                ),
                (
                    "ai_verification_result",
                    models.JSONField(
                        blank=True,
                        help_text="AI verification results for this specific image",
                        null=True,
                    ),
                ),
                (
                    "ai_confidence_score",
                    models.FloatField(
                        blank=True,
                        help_text="AI confidence score for this image",
                        null=True,
                    ),
                ),
                (
                    "is_verified_by_ai",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this image passed AI verification",
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                (
                    "file_hash",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 hash of the image file for deduplication",
                        max_length=64,
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the image was uploaded"
                    ),
                ),
                (
                    "hazard_report",
                    models.ForeignKey(
                        help_text="The hazard report this image belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hazard_images",
                        to="users.oceanhazardreport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hazard Image",
                "verbose_name_plural": "Hazard Images",
                "ordering": ["uploaded_at"],
            },
        ),
        migrations.AddIndex(
            model_name="oceanhazardreport",
            index=models.Index(
                fields=["status", "reported_at"], name="users_ocean_status_2b5cbd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="oceanhazardreport",
            index=models.Index(
                fields=["hazard_type", "status"], name="users_ocean_hazard__4998ca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="oceanhazardreport",
            index=models.Index(
                fields=["state", "district"], name="users_ocean_state_1ad12b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="oceanhazardreport",
            index=models.Index(
                fields=["reported_by", "reported_at"],
                name="users_ocean_reporte_386f32_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="hazardimage",
            index=models.Index(
                fields=["hazard_report", "uploaded_at"],
                name="users_hazar_hazard__8057e1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="hazardimage",
            index=models.Index(
                fields=["is_verified_by_ai"], name="users_hazar_is_veri_441385_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hazardimage",
            index=models.Index(
                fields=["file_hash"], name="users_hazar_file_ha_acc462_idx"
            ),
        ),
    ]
