# Generated by Django 5.2 on 2025-10-03 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_oceanhazardreport_hazardimage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubAuthorityTeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_date", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("first_name", models.CharField(default="", max_length=30)),
                ("middle_name", models.CharField(blank=True, max_length=50, null=True)),
                ("last_name", models.CharField(default="", max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone_number", models.CharField(default="", max_length=15)),
                ("role", models.CharField(default="team_member", max_length=50)),
                (
                    "designation",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("district", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "nagar_panchayat",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("village", models.CharField(blank=True, max_length=100, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "government_service_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "document_proof",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="sub_authority_team_member_documents/",
                    ),
                ),
                ("can_view_reports", models.BooleanField(default=False)),
                ("can_approve_reports", models.BooleanField(default=False)),
                ("can_manage_teams", models.BooleanField(default=False)),
                ("password_hash", models.CharField(default="", max_length=255)),
                (
                    "sub_authority",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_authority_team_members",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
