# Generated by Django 5.2 on 2026-03-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_subauthorityteammember"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_picture",
            field=models.FileField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
        migrations.AlterField(
            model_name="oceanhazardreport",
            name="hazard_type",
            field=models.CharField(
                choices=[
                    ("tsunami", "Tsunami Warning"),
                    ("storm-surge", "Storm Surge"),
                    ("high-waves", "High Waves"),
                    ("flooding", "Coastal Flooding"),
                    ("debris", "Marine Debris"),
                    ("pollution", "Water Pollution"),
                    ("erosion", "Coastal Erosion"),
                    ("wildlife", "Marine Wildlife Issue"),
                    ("water_disaster", "Water Disaster"),
                    ("oil_spill", "Oil Spill"),
                    ("cora_bleaching", "Coral Bleaching"),
                    ("normal", "Normal Condition"),
                    ("other", "Other Hazard"),
                ],
                help_text="Type of ocean hazard reported",
                max_length=50,
            ),
        ),
    ]
