# Generated by Django 5.2 on 2026-03-24 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_customuser_profile_picture_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_premium",
            field=models.BooleanField(default=False),
        ),
    ]
